export const LOAD_SUPPLIER_MASTER_REQUEST = "LOAD_SUPPLIER_MASTER_REQUEST";
export const LOAD_SUPPLIER_MASTER_SUCCESS = "LOAD_SUPPLIER_MASTER_SUCCESS";
export const LOAD_SUPPLIER_MASTER_FAIL = "LOAD_SUPPLIER_MASTER_FAIL";

export const ALL_SUPPLIER_MASTER_REQUEST = "ALL_SUPPLIER_MASTER_REQUEST";
export const ALL_SUPPLIER_MASTER_SUCCESS = "ALL_SUPPLIER_MASTER_SUCCESS";
export const ALL_SUPPLIER_MASTER_FAIL = "ALL_SUPPLIER_MASTER_FAIL";

export const ALL_BIN_TYPE_MASTER_REQUEST = "ALL_BIN_TYPE_MASTER_REQUEST";
export const ALL_BIN_TYPE_MASTER_SUCCESS = "ALL_BIN_TYPE_MASTER_SUCCESS";
export const ALL_BIN_TYPE_MASTER_FAIL = "ALL_BIN_TYPE_MASTER_FAIL";

export const LOAD_COSTING_MASTER_REQUEST = "LOAD_COSTING_MASTER_REQUEST";
export const LOAD_COSTING_MASTER_SUCCESS = "LOAD_COSTING_MASTER_SUCCESS";
export const LOAD_COSTING_MASTER_FAIL = "LOAD_COSTING_MASTER_FAIL";

export const ALL_LOADING_MASTER_REQUEST = "ALL_LOADING_MASTER_REQUEST";
export const ALL_LOADING_MASTER_SUCCESS = "ALL_LOADING_MASTER_SUCCESS";
export const ALL_LOADING_MASTER_FAIL = "ALL_LOADING_MASTER_FAIL";

export const ALL_UOM_MASTER_REQUEST = "ALL_UOM_MASTER_REQUEST";
export const ALL_UOM_MASTER_SUCCESS = "ALL_UOM_MASTER_SUCCESS";
export const ALL_UOM_MASTER_FAIL = "ALL_UOM_MASTER_FAIL";

export const ALL_AUOM_MASTER_REQUEST = "ALL_AUOM_MASTER_REQUEST";
export const ALL_AUOM_MASTER_SUCCESS = "ALL_AUOM_MASTER_SUCCESS";
export const ALL_AUOM_MASTER_FAIL = "ALL_AUOM_MASTER_FAIL";

export const ALL_FORKLIFT_OPERATOR_MASTER_REQUEST =
  "ALL_FORKLIFT_OPERATOR_MASTER_REQUEST";
export const ALL_FORKLIFT_OPERATOR_MASTER_SUCCESS =
  "ALL_FORKLIFT_OPERATOR_MASTER_SUCCESS";
export const ALL_FORKLIFT_OPERATOR_MASTER_FAIL =
  "ALL_FORKLIFT_OPERATOR_MASTER_FAIL";

export const ALL_FORKLIFT_OPERATOR_OUTBOUND_MASTER_REQUEST =
  "ALL_FORKLIFT_OPERATOR_OUTBOUND_MASTER_REQUEST";
export const ALL_FORKLIFT_OPERATOR_OUTBOUND_MASTER_SUCCESS =
  "ALL_FORKLIFT_OPERATOR_OUTBOUND_MASTER_SUCCESS";
export const ALL_FORKLIFT_OPERATOR_OUTBOUND_MASTER_FAIL =
  "ALL_FORKLIFT_OPERATOR_OUTBOUND_MASTER_FAIL";

export const ALL_CROSS_DOCK_MASTER_REQUEST = "ALL_CROSS_DOCK_MASTER_REQUEST";
export const ALL_CROSS_DOCK_MASTER_SUCCESS = "ALL_CROSS_DOCK_MASTER_SUCCESS";
export const ALL_CROSS_DOCK_MASTER_FAIL = "ALL_CROSS_DOCK_MASTER_FAIL";

export const ALL_PRODUCTION_REQUEST = "ALL_PRODUCTION_REQUEST";
export const ALL_PRODUCTION_SUCCESS = "ALL_PRODUCTION_SUCCESS";
export const ALL_PRODUCTION_FAIL = "ALL_PRODUCTION_FAIL";

export const ALL_OUTBOUND_REQUEST = "ALL_OUTBOUND_REQUEST";
export const ALL_OUTBOUND_SUCCESS = "ALL_OUTBOUND_SUCCESS";
export const ALL_OUTBOUND_FAIL = "ALL_OUTBOUND_FAIL";

export const ALL_BIN_TABLE_REQUEST = "ALL_BIN_TABLE_REQUEST";
export const ALL_BIN_TABLE_SUCCESS = "ALL_BIN_TABLE_SUCCESS";
export const ALL_BIN_TABLE_FAIL = "ALL_BIN_TABLE_FAIL";

export const ALL_STOCK_REPORT_REQUEST = "ALL_STOCK_REPORT_REQUEST";
export const ALL_STOCK_REPORT_SUCCESS = "ALL_STOCK_REPORT_SUCCESS";
export const ALL_STOCK_REPORT_FAIL = "ALL_STOCK_REPORT_FAIL";

export const ALL_TRANSACTION_REQUEST = "ALL_TRANSACTION_REQUEST";
export const ALL_TRANSACTION_SUCCESS = "ALL_TRANSACTION_SUCCESS";
export const ALL_TRANSACTION_FAIL = "ALL_TRANSACTION_FAIL";

export const ALL_TRANSACTION_OUTBOND_REQUEST =
  "ALL_TRANSACTION_OUTBOND_REQUEST";
export const ALL_TRANSACTION_OUTBOND_SUCCESS =
  "ALL_TRANSACTION_OUTBOND_SUCCESS";
export const ALL_TRANSACTION_OUTBOND_FAIL = "ALL_TRANSACTION_OUTBOND_FAIL";

export const ALL_UNLOADING_MASTER_REQUEST = "ALL_UNLOADING_MASTER_REQUEST";
export const ALL_UNLOADING_MASTER_SUCCESS = "ALL_UNLOADING_MASTER_SUCCESS";
export const ALL_UNLOADING_MASTER_FAIL = "ALL_UNLOADING_MASTER_FAIL";

export const ALL_COSTING_MASTER_REQUEST = "ALL_COSTING_MASTER_REQUEST";
export const ALL_COSTING_MASTER_SUCCESS = "ALL_COSTING_MASTER_SUCCESS";
export const ALL_COSTING_MASTER_FAIL = "ALL_COSTING_MASTER_FAIL";

export const LOAD_PRODUCT_MASTER_REQUEST = "LOAD_PRODUCT_MASTER_REQUEST";
export const LOAD_PRODUCT_MASTER_SUCCESS = "LOAD_PRODUCT_MASTER_SUCCESS";
export const LOAD_PRODUCT_MASTER_FAIL = "LOAD_PRODUCT_MASTER_FAIL";

export const ALL_PRODUCT_MASTER_REQUEST = "ALL_PRODUCT_MASTER_REQUEST";
export const ALL_PRODUCT_MASTER_SUCCESS = "ALL_PRODUCT_MASTER_SUCCESS";
export const ALL_PRODUCT_MASTER_FAIL = "ALL_PRODUCT_MASTER_FAIL";

//pallete master
export const ALL_PALLETE_MASTER_REQUEST = "ALL_PALLETE_MASTER_REQUEST";
export const ALL_PALLETE_MASTER_SUCCESS = "ALL_PALLETE_MASTER_SUCCESS";
export const ALL_PALLETE_MASTER_FAIL = "ALL_PALLETE_MASTER_FAIL";

//VENDOR master
export const ALL_VENDOR_MASTER_REQUEST = "ALL_VENDOR_MASTER_REQUEST";
export const ALL_VENDOR_MASTER_SUCCESS = "ALL_VENDOR_MASTER_SUCCESS";
export const ALL_VENDOR_MASTER_FAIL = "ALL_VENDOR_MASTER_FAIL";

//CUSTOMER_TYPE master
export const ALL_CUSTOMER_TYPE_MASTER_REQUEST =
  "ALL_CUSTOMER_TYPE_MASTER_REQUEST";
export const ALL_CUSTOMER_TYPE_MASTER_SUCCESS =
  "ALL_CUSTOMER_TYPE_MASTER_SUCCESS";
export const ALL_CUSTOMER_TYPE_MASTER_FAIL = "ALL_CUSTOMER_TYPE_MASTER_FAIL";

//fabricColor master
export const ALL_FABRIC_COLOR_MASTER_REQUEST =
  "ALL_FABRIC_COLOR_MASTER_REQUEST";
export const ALL_FABRIC_COLOR_MASTER_SUCCESS =
  "ALL_FABRIC_COLOR_MASTER_SUCCESS";
export const ALL_FABRIC_COLOR_MASTER_FAIL = "ALL_FABRIC_COLOR_MASTER_FAIL";

//party master
export const ALL_STORAGE_TYPE_MASTER_REQUEST =
  "ALL_STORAGE_TYPE_MASTER_REQUEST";
export const ALL_STORAGE_TYPE_MASTER_SUCCESS =
  "ALL_STORAGE_TYPE_MASTER_SUCCESS";
export const ALL_STORAGE_TYPE_MASTER_FAIL = "ALL_STORAGE_TYPE_MASTER_FAIL";

//INBOUND_GATE_ENTRY
export const ALL_INBOUND_GATE_ENTRY_REQUEST = "ALL_INBOUND_GATE_ENTRY_REQUEST";
export const ALL_INBOUND_GATE_ENTRY_SUCCESS = "ALL_INBOUND_GATE_ENTRY_SUCCESS";
export const ALL_INBOUND_GATE_ENTRY_FAIL = "ALL_INBOUND_GATE_ENTRY_FAIL";
//OUTBOUND_GATE_ENTRY
export const ALL_OUTBOUND_GATE_ENTRY_REQUEST =
  "ALL_OUTBOUND_GATE_ENTRY_REQUEST";
export const ALL_OUTBOUND_GATE_ENTRY_SUCCESS =
  "ALL_OUTBOUND_GATE_ENTRY_SUCCESS";
export const ALL_OUTBOUND_GATE_ENTRY_FAIL = "ALL_OUTBOUND_GATE_ENTRY_FAIL";
//STORAGE_SEARCH_MASTER
export const ALL_STORAGE_SEARCH_MASTER_REQUEST =
  "ALL_STORAGE_SEARCH_MASTER_REQUEST";
export const ALL_STORAGE_SEARCH_MASTER_SUCCESS =
  "ALL_STORAGE_SEARCH_MASTER_SUCCESS";
export const ALL_STORAGE_SEARCH_MASTER_FAIL = "ALL_STORAGE_SEARCH_MASTER_FAIL";

// item name master
export const ALL_CUSTOMER_MASTER_REQUEST = "ALL_CUSTOMER_MASTER_REQUEST";
export const ALL_CUSTOMER_MASTER_SUCCESS = "ALL_CUSTOMER_MASTER_SUCCESS";
export const ALL_CUSTOMER_MASTER_FAIL = "ALL_CUSTOMER_MASTER_FAIL";

// _BIN_MASTER
export const ALL_BIN_MASTER_REQUEST = "ALL_BIN_MASTER_REQUEST";
export const ALL_BIN_MASTER_SUCCESS = "ALL_BIN_MASTER_SUCCESS";
export const ALL_BIN_MASTER_FAIL = "ALL_BIN_MASTER_FAIL";

// VEHICLE master
export const ALL_VEHICLE_MASTER_REQUEST = "ALL_VEHICLE_MASTER_REQUEST";
export const ALL_VEHICLE_MASTER_SUCCESS = "ALL_VEHICLE_MASTER_SUCCESS";
export const ALL_VEHICLE_MASTER_FAIL = "ALL_VEHICLE_MASTER_FAIL";

//fabric master
export const ALL_FABRIC_MASTER_REQUEST = "ALL_FABRIC_MASTER_REQUEST";
export const ALL_FABRIC_MASTER_SUCCESS = "ALL_FABRIC_MASTER_SUCCESS";
export const ALL_FABRIC_MASTER_FAIL = "ALL_FABRIC_MASTER_FAIL";

//TRUCK_LOADING
export const ALL_TRUCK_LOADING_REQUEST = "ALL_TRUCK_LOADING_REQUEST";
export const ALL_TRUCK_LOADING_SUCCESS = "ALL_TRUCK_LOADING_SUCCESS";
export const ALL_TRUCK_LOADING_FAIL = "ALL_TRUCK_LOADING_FAIL";
