export const LOAD_SUPPLIER_MASTER_REQUEST = "LOAD_SUPPLIER_MASTER_REQUEST";
export const LOAD_SUPPLIER_MASTER_SUCCESS = "LOAD_SUPPLIER_MASTER_SUCCESS";
export const LOAD_SUPPLIER_MASTER_FAIL = "LOAD_SUPPLIER_MASTER_FAIL";

export const ALL_SUPPLIER_MASTER_REQUEST = "ALL_SUPPLIER_MASTER_REQUEST";
export const ALL_SUPPLIER_MASTER_SUCCESS = "ALL_SUPPLIER_MASTER_SUCCESS";
export const ALL_SUPPLIER_MASTER_FAIL = "ALL_SUPPLIER_MASTER_FAIL";

export const LOAD_COSTING_MASTER_REQUEST = "LOAD_COSTING_MASTER_REQUEST";
export const LOAD_COSTING_MASTER_SUCCESS = "LOAD_COSTING_MASTER_SUCCESS";
export const LOAD_COSTING_MASTER_FAIL = "LOAD_COSTING_MASTER_FAIL";

export const ALL_LOADING_MASTER_REQUEST = "ALL_LOADING_MASTER_REQUEST";
export const ALL_LOADING_MASTER_SUCCESS = "ALL_LOADING_MASTER_SUCCESS";
export const ALL_LOADING_MASTER_FAIL = "ALL_LOADING_MASTER_FAIL";

export const ALL_FORKLIFT_OPERATOR_MASTER_REQUEST =
  "ALL_FORKLIFT_OPERATOR_MASTER_REQUEST";
export const ALL_FORKLIFT_OPERATOR_MASTER_SUCCESS =
  "ALL_FORKLIFT_OPERATOR_MASTER_SUCCESS";
export const ALL_FORKLIFT_OPERATOR_MASTER_FAIL =
  "ALL_FORKLIFT_OPERATOR_MASTER_FAIL";

export const ALL_CROSS_DOCK_MASTER_REQUEST =
  "ALL_CROSS_DOCK_MASTER_REQUEST";
export const ALL_CROSS_DOCK_MASTER_SUCCESS =
  "ALL_CROSS_DOCK_MASTER_SUCCESS";
export const ALL_CROSS_DOCK_MASTER_FAIL = "ALL_CROSS_DOCK_MASTER_FAIL";

export const ALL_PRODUCTION_REQUEST = "ALL_PRODUCTION_REQUEST";
export const ALL_PRODUCTION_SUCCESS = "ALL_PRODUCTION_SUCCESS";
export const ALL_PRODUCTION_FAIL = "ALL_PRODUCTION_FAIL";

export const ALL_BIN_TABLE_REQUEST = "ALL_BIN_TABLE_REQUEST";
export const ALL_BIN_TABLE_SUCCESS = "ALL_BIN_TABLE_SUCCESS";
export const ALL_BIN_TABLE_FAIL = "ALL_BIN_TABLE_FAIL";

export const ALL_UNLOADING_MASTER_REQUEST = "ALL_UNLOADING_MASTER_REQUEST";
export const ALL_UNLOADING_MASTER_SUCCESS = "ALL_UNLOADING_MASTER_SUCCESS";
export const ALL_UNLOADING_MASTER_FAIL = "ALL_UNLOADING_MASTER_FAIL";

export const ALL_COSTING_MASTER_REQUEST = "ALL_COSTING_MASTER_REQUEST";
export const ALL_COSTING_MASTER_SUCCESS = "ALL_COSTING_MASTER_SUCCESS";
export const ALL_COSTING_MASTER_FAIL = "ALL_COSTING_MASTER_FAIL";

export const LOAD_PRODUCT_MASTER_REQUEST = "LOAD_PRODUCT_MASTER_REQUEST";
export const LOAD_PRODUCT_MASTER_SUCCESS = "LOAD_PRODUCT_MASTER_SUCCESS";
export const LOAD_PRODUCT_MASTER_FAIL = "LOAD_PRODUCT_MASTER_FAIL";

export const ALL_PRODUCT_MASTER_REQUEST = "ALL_PRODUCT_MASTER_REQUEST";
export const ALL_PRODUCT_MASTER_SUCCESS = "ALL_PRODUCT_MASTER_SUCCESS";
export const ALL_PRODUCT_MASTER_FAIL = "ALL_PRODUCT_MASTER_FAIL";

//pallete master
export const ALL_PALLETE_MASTER_REQUEST = "ALL_PALLETE_MASTER_REQUEST";
export const ALL_PALLETE_MASTER_SUCCESS = "ALL_PALLETE_MASTER_SUCCESS";
export const ALL_PALLETE_MASTER_FAIL = "ALL_PALLETE_MASTER_FAIL";

//VENDOR master
export const ALL_VENDOR_MASTER_REQUEST = "ALL_VENDOR_MASTER_REQUEST";
export const ALL_VENDOR_MASTER_SUCCESS = "ALL_VENDOR_MASTER_SUCCESS";
export const ALL_VENDOR_MASTER_FAIL = "ALL_VENDOR_MASTER_FAIL";

//fabricColor master
export const ALL_FABRIC_COLOR_MASTER_REQUEST =
  "ALL_FABRIC_COLOR_MASTER_REQUEST";
export const ALL_FABRIC_COLOR_MASTER_SUCCESS =
  "ALL_FABRIC_COLOR_MASTER_SUCCESS";
export const ALL_FABRIC_COLOR_MASTER_FAIL = "ALL_FABRIC_COLOR_MASTER_FAIL";

//party master
export const ALL_STORAGE_TYPE_MASTER_REQUEST =
  "ALL_STORAGE_TYPE_MASTER_REQUEST";
export const ALL_STORAGE_TYPE_MASTER_SUCCESS =
  "ALL_STORAGE_TYPE_MASTER_SUCCESS";
export const ALL_STORAGE_TYPE_MASTER_FAIL = "ALL_STORAGE_TYPE_MASTER_FAIL";

//unit master
export const ALL_UNIT_MASTER_REQUEST = "ALL_UNIT_MASTER_REQUEST";
export const ALL_UNIT_MASTER_SUCCESS = "ALL_UNIT_MASTER_SUCCESS";
export const ALL_UNIT_MASTER_FAIL = "ALL_UNIT_MASTER_FAIL";
//STORAGE_SEARCH_MASTER
export const ALL_STORAGE_SEARCH_MASTER_REQUEST =
  "ALL_STORAGE_SEARCH_MASTER_REQUEST";
export const ALL_STORAGE_SEARCH_MASTER_SUCCESS =
  "ALL_STORAGE_SEARCH_MASTER_SUCCESS";
export const ALL_STORAGE_SEARCH_MASTER_FAIL = "ALL_STORAGE_SEARCH_MASTER_FAIL";

// item name master
export const ALL_CUSTOMER_MASTER_REQUEST = "ALL_CUSTOMER_MASTER_REQUEST";
export const ALL_CUSTOMER_MASTER_SUCCESS = "ALL_CUSTOMER_MASTER_SUCCESS";
export const ALL_CUSTOMER_MASTER_FAIL = "ALL_CUSTOMER_MASTER_FAIL";

// _BIN_MASTER
export const ALL_BIN_MASTER_REQUEST = "ALL_BIN_MASTER_REQUEST";
export const ALL_BIN_MASTER_SUCCESS = "ALL_BIN_MASTER_SUCCESS";
export const ALL_BIN_MASTER_FAIL = "ALL_BIN_MASTER_FAIL";

// VEHICLE master
export const ALL_VEHICLE_MASTER_REQUEST = "ALL_VEHICLE_MASTER_REQUEST";
export const ALL_VEHICLE_MASTER_SUCCESS = "ALL_VEHICLE_MASTER_SUCCESS";
export const ALL_VEHICLE_MASTER_FAIL = "ALL_VEHICLE_MASTER_FAIL";

//fabric master
export const ALL_FABRIC_MASTER_REQUEST = "ALL_FABRIC_MASTER_REQUEST";
export const ALL_FABRIC_MASTER_SUCCESS = "ALL_FABRIC_MASTER_SUCCESS";
export const ALL_FABRIC_MASTER_FAIL = "ALL_FABRIC_MASTER_FAIL";
